### ISSUE TITLE
Could not install 3.4.0 using pip

### ISSUE THREAD

**Issue by adieyal** [ijl/orjson#128]
```
# pip3 install orjson
Collecting orjson
  Using cached https://files.pythonhosted.org/packages/ca/ab/cece004aaae000741d059dcb9b1f6f62a6a5ecb2e11b3ecca09e6180c327/orjson-3.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-aup3c1nd/orjson/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-aup3c1nd/orjson/
```

3.3.1 works though:
`pip3 install orjson==3.3.1`

Using ubuntu bionic

**Comment by ijl** [comment]
In this environment you have not upgraded `pip` and the distro's version does not support `manylinux2014`, yeah? If you can check whether it installs `manylinux2010` wheels, those can probably be shipped.

**Comment by plartemyev** [comment]
I've fixed this issue on Amazon Linux 2 by updating the pip itself. Apparently, manylinux2014 requires pip >= 19.3.

**Comment by SalomonSmeke** [comment]
I also was on manylinux2010, I suspect many people who dont update pip will also be. No need to fix it if you dont think it should be @ijl ! But +1 that I hit this too. In my case its due to docker images which build 3.7.7 and dont update pip.

I fixed it in my use-case by just dropping a pip upgrade in the docker file; no big. But the error message is a bit confusing, might be worth dropping a line in the setup guide that you might need to upgrade pip.

**Comment by adieyal** [comment]
Agreed re adding a note in the documentation. I did however encounter the
issue when installing another library that depends on orjson. Downstream
users may not see the note.

**Comment by ijl** [comment]
So are manylinux2010 wheels installable in the same environments out of the box?
