### ISSUE TITLE
Support serialization of NamedTuples by default

### ISSUE THREAD

**Issue by avanov** [ijl/orjson#15]
Hi! It would be cool to have it implemented. So far` simplejson` seems to be the only one that does it right (stdlib's `json` serializes named tuples as list values, which is hardly a desired default behaviour):

```python
>>> from simplejson import dumps
>>> from typing import NamedTuple
>>> class X(NamedTuple):
...     x: int
... 
>>> dumps(X(1))
'{"x": 1}'
```

**Comment by ijl** [comment]
rapidjson and ultrajson also serialize a namedtuple as a list. I think it's undesirable to break convention with the standard library and other libraries on this. It doesn't look appealing to me to make it an option, because one, it can't be serialized any faster than calling `default` (there is no C API), and two, the library doesn't try to serialize subclasses. Instead the way I think of the behavior is "give me a simple type with a known output or transform your object into a simple type through `default`."

**Comment by avanov** [comment]
> rapidjson and ultrajson also serialize a namedtuple as a list.

There's however some work being done for an override for it in 3.8 (supposedly):

* https://bugs.python.org/issue23473
* https://bugs.python.org/issue12657

**Comment by avanov** [comment]
I think I should have mentioned it right in the first message, that it's more of an invitation for a discussion rather than a call for action, so I appreciate your quick feedback on that matter.

**Comment by ijl** [comment]
Ok, if namedtuple becomes a simple type like a dict that helps.

**Comment by ymoran00** [comment]
Agree on that need.
Is there another way to override the current Encoder and export a namedtuple as a dict and not a list?

**Comment by ethanhs** [comment]
(Hopefully it is okay for me to share this)

@avanov you may also be interested in my experiment abserde: https://github.com/ethanhs/abserde

**Comment by ijl** [comment]
python3.8 still serializes as a list so I see nothing to do. I suggest using `default`.

**Comment by belm0** [comment]
It's unfortunate not to support a type that `json` handles.  Because if I'm wrapping `orjson` for compatibility with `json`, this seems to be the only point to need an unknown-type handler.  But if the caller of the wrapped `dumps()` is supplying `default=` himself, then I have to implement chaining with the NamedTuple handler...

**Comment by gnzsnz** [comment]
this is a recipe for namedtuples

https://stackoverflow.com/a/61948700/13067413

```python
import orjson
from typing import NamedTuple

class Rectangle(NamedTuple):
    width: int
    height: int

def default(obj):
    if hasattr(obj, '_asdict'):
        return obj._asdict()

rectangle = Rectangle(width=10, height=20)
print(orjson.dumps(rectangle, default=default))

```
