### ISSUE TITLE
Option to serialize `NaN` and `Infinity` as strings

### ISSUE THREAD

**Issue by loichuder** [ijl/orjson#170]
Hello :wave: 

I would like to be able to distinguish between `NaN` and `(-)Infinity` after serialization for visualization purposes. For now, this is not possible as both are converted to `null`.

Would it be possible/make sense to have an option (something like: `OPT_SERIALIZE_NAN`) to serialize `NaN` and `(-)Infinity` as strings (`"NaN"`, `"Infinity"` and `"-Infinity"`) ?

**Comment by ijl** [comment]
How widely useful it is to produce non-compliant JSON like this? Is this a hack with one client or a general thing for data visualization? Would you expect the parser to handle NaN, Infinity, -Infinity? It wouldn't be acceptable to serialize something that causes an error on deserialization. I don't have a principled objection if this is widely used but it seems difficult to include.

**Comment by loichuder** [comment]
> How widely useful it is to produce non-compliant JSON like this? 

Bear with my ignorance here, but in what sense would having strings instead of `null` not be compliant ?

> Is this a hack with one client or a general thing for data visualization? 

I am not aware of any other strategy that would allow to distinguish between `NaN` and `Infinity` after JSON serialization 
but I can't speak for all data visualizations using JSON. For the record, [bokeh](https://docs.bokeh.org/en/latest/) does not allow NaN at all when serializing to JSON: https://github.com/bokeh/bokeh/issues/5581

> Would you expect the parser to handle NaN, Infinity, -Infinity? It wouldn't be acceptable to serialize something that causes an error on deserialization. 

A valid point. It would indeed make sense for the parser to parse back `"NaN"` into `NaN` and so on.

> I don't have a principled objection if this is widely used but it seems difficult to include.

Again, I can not assure that this would be widely used. I proposed to add an option as I find it similar to `OPT_NON_STR_KEYS`: it is an opt-in thing, not everyone is going to use it, but it is handy to have it there for the people who want it.

**Comment by polakowo** [comment]
@ijl I'm having the same need of distinguishing between NaN and Infinity, as they have totally different purposes in my use case (also related to data science) and I sadly see no workaround on how to fix this lost information after serialization. As @loichuder suggested, a simple flag would be sufficient to make it compatible with other libs, or let the user specify the representation. This is the only limitation that holds me back from using this awesome library in a bigger project.

**Comment by jack-pappas** [comment]
Potential alternate solution here -- the [JSON5](https://json5.org/) format is a lightly-extended version of JSON which includes support for IEEE754 ``NaN``, +/-``Infinity`` and hexadecimal numbers (which could be a nice workaround for Javascript's only supporting 53-bit integers). Maybe _orjson_ could have an ``OPT_JSON5`` option which allows users to at least output the JSON5-formatted data for when they need to preserve these values?

**Comment by ijl** [comment]
I have no interest in figuring this out, but someone can open a new issue with a concrete proposal.

**Comment by max0x7ba** [comment]
> Potential alternate solution here -- the [JSON5](https://json5.org/) format is a lightly-extended version of JSON which includes support for IEEE754 `NaN`, +/-`Infinity` and hexadecimal numbers (which could be a nice workaround for Javascript's only supporting 53-bit integers). Maybe _orjson_ could have an `OPT_JSON5` option which allows users to at least output the JSON5-formatted data for when they need to preserve these values?

Was about to mention that JSON not being able to express IEEE754 `NaN`, +/-`Infinity` is an oversight/deficiency/bug in original JSON specification fixed in JSON5. But you already did so.

Strict compliance to this deficiency/bug in original JSON specification is a serious limitation for this library domain/applicability, rather than a desirable virtue. Python standard `json` library doesn't have this limitation, neither does `ujson`.

Projects I have worked on in the last 15 years, all required/used JSON libraries that preserve IEEE754 `NaN`, +/-`Infinity` values. In browsers, people have used `eval` instead of `JSON.parse` to parse JSONs with IEEE754 `NaN`, +/-`Infinity` values. Of course, `eval` risks executing malicious code, so that it must only be used to parse JSONs of known provenance. But it demonstrates clearly that people value IEEE754 `NaN`, +/-`Infinity` in their JSONs more than "security" or "strict compliance" to bugs in standards.

I was excited about switching my codebase from `json` and `ujson` to `orjson`, spent a couple of days to make that happen. Only to find out that `orjson` produced JSONs are pretty much worthless without IEEE754 `NaN`, +/-`Infinity` in them, break absolutely everything reading those JSONs.

Being "useful and helpful" and "strict compiliance to JSON" are qualities that do not overlap, unfortunately.
