### ISSUE TITLE
ImportError on CentOS 7

### ISSUE THREAD

**Issue by davidgaleano** [ijl/orjson#2]
Installed with:

    pip3 install --user --upgrade orjson

Fails on import:

    import orjson
    ImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/davidgaleano/.local/lib/python3.6/site-packages/orjson.cpython-36m-x86_64-linux-gnu.so)

The python version is 3.6.3, and the CentOS version is 7.4.1708.

**Comment by ijl** [comment]
Ok, this needs https://github.com/rust-lang/rust/issues/56849, then can look into building Linux wheel using the mmanylinux1 container. https://github.com/PyO3/pyo3-pack/issues/47.

**Comment by joar** [comment]
@ijl If it helps, I've managed to build manylinux wheels successfully for https://github.com/joar/rust-csv-py by instaling an older rust nightly.

In any case, I have some code that might be helpful when building pyo3 libraries using the manylinux1 docker image.

1. [Makefile target `build-wheels-manylinux`](https://github.com/joar/rust-csv-py/blob/05f96cab33e11f844ef2c66f526d0eda20e80dfe/Makefile#L130-L139) (called from [travis/deploy.sh](https://github.com/joar/rust-csv-py/blob/master/travis/deploy.sh))
2. [travis/build-wheels-manylinux.sh](https://github.com/joar/rust-csv-py/blob/master/travis/build-wheels-manylinux.sh) (executed inside the manylinux docker image). Note: I'm using setuptools-rust, I think the pyo3-pack version of this script might be shorter.

**Comment by ijl** [comment]
@joar thanks, I'll revisit this issue later.

**Comment by konstin** [comment]
FYI pyo3-pack got a working docker image now that should make this. I've only used the image with the testing crates yet so please feel free to open an issue if there's any problem or question with the image.

**Comment by ijl** [comment]
I attempted this and it was not practical. I've documented that glibc earlier than 2.18 is not supported in the README (2d0c76e92402b0d7c69cf52660ae805fb731730f). You can build a wheel from source on your own system, however.

**Comment by konstin** [comment]
@ijl Could you tell a bit more about what the problem with the docker container was?

**Comment by ijl** [comment]
@konstin it wasn't a problem with the container you've published, more that working with Azure Pipelines was failing and too time consuming.

**Comment by pskopnik** [comment]
I just built a conforming `manylinux1` wheel using the [konstin2/maturin:master][konstin2-maturin] image. Tests are passing.

Would you reconsider testing whether this is feasible on Azure? I used very similar commands to the pipeline specification.

These changes are required from my point of view:

 * https://github.com/ijl/orjson/blob/master/ci/azure-linux-container.yml

   * Remove interpreter, add Python tag variable.

     The tag would correspond to the directory name of the Python version:
     ```shell
     $ ls /opt/python/
     cp27-cp27m  cp27-cp27mu  cp34-cp34m  cp35-cp35m  cp36-cp36m  cp37-cp37m  cp38-cp38
     ```

   * Add the Python binary directory to the beginning of PATH. `python`, `pip` and co. will then resolve to the correct binary.

     ```shell
     $ ls /opt/python/cp37-cp37m/bin
     2to3      auditwheel    easy_install-3.7  idle3.7  pip3    __pycache__  pydoc3.7  python3    python3.7-config  python3.7m-config  pyvenv      readelf.py
     2to3-3.7  easy_install  idle3             pip      pip3.7  pydoc3       python    python3.7  python3.7m        python3-config     pyvenv-3.7  wheel
     ```

 * Restructure to use the maturin image, use the Python tag instead of the interpreter variable: https://github.com/ijl/orjson/blob/master/ci/azure-pipelines.yml#L17..L67

[konstin2-maturin]: https://hub.docker.com/r/konstin2/maturin

**Comment by pskopnik** [comment]
I can probably just create a PR. Will the pipelines execute?
