### ISSUE TITLE
3.6.6 silent crash on windows (packed by pyinstaller)

### ISSUE THREAD

**Issue by rpodgorny** [ijl/orjson#235]
we're using orjson within a pretty-complex application (along with pyside6 and other huge libraries). the final product is being packaged for windows using pyinstaller.

lately, our app fails to start. there's some cryptic message about application crash in windows event log. after investigating, it seems the crash is caused by orjson-3.6.6 - when built with 3.6.5 (everything else being the same), it runs correctly.

i don't have much time to investigate further right now. hopefully you'll have the idea what might be wrong... ...if not, i'll try to provide more info later...

**Comment by ijl** [comment]
If you find an issue with your custom build setup traced to this library I will accept a patch.

**Comment by ThirVondukr** [comment]
@ijl 
I've also encountered this issue with `orjson==3.6.6` in my project, but for some reason i wasn't able to reproduce crash with this specific version, in separate project it crashes with `3.6.*` (i didn't test versions under 3.6),  versions of ojrson.
I hope you would be able to reproduce it: https://github.com/ThirVondukr/pyinstaller-orjson

**Comment by himbeles** [comment]
> @ijl
> I've also encountered this issue with `orjson==3.6.6` in my project, but for some reason i wasn't able to reproduce crash with this specific version, in separate project it crashes with `3.6.*` (i didn't test versions under 3.6), versions of ojrson.
> I hope you would be able to reproduce it: https://github.com/ThirVondukr/pyinstaller-orjson

I can reproduce the bug with the code in the linked repo. On Windows 10,  Python 3.9.10 and Python 3.10.2 . Silent crash on import.

**Comment by Traktormaster** [comment]
Version `3.6.6` also crashes an application for me. I'm using Python 3.9.9 on macOS 10.14. It's very strange because the crash *only* happens when the application is run from an application bundle. When I'm running it from the virtualenv it works as expected. I'm using cx_Freeze to create the app btw.

If I downgrade to version `3.6.5` the built app works.

**Comment by himbeles** [comment]
For me, a pyinstaller hook for hidden stdlib imports and numpy import fixed the issue. 
I have contributed it as PR to [https://github.com/pyinstaller/pyinstaller-hooks-contrib](https://github.com/pyinstaller/pyinstaller-hooks-contrib): 

https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/08dbcf24a798f43ac3a373f89cee081855589675/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-orjson.py

The problem is the forced import of modules in `src/typeref.rs`, which pyinstaller doesn't know about.

**Comment by ThirVondukr** [comment]
@himbeles I'm curious what is has to do with numpy 🤔

**Comment by himbeles** [comment]
`orjson` supports `numpy` encoding/decoding. On orjson import, it tries to load the numpy library to detect different types it could encounter during encoding/decoding. Adding numpy to the hook hidden imports has no effect if numpy is not installed in your virtual environment. Pyinstaller will not crash, but instead just not bundle it in the executable and throw a warning. Have you tried if the hook works for you?

**Comment by himbeles** [comment]
throw the `hook-orjson.py` file into a `hooks` directory and call pyinstaller with the `--additional-hooks-dir=hooks` argument.

**Comment by ThirVondukr** [comment]
Not yet tried it, would be able to in a couple of days, i just downgraded orjson to 3.6.5 for now

**Comment by himbeles** [comment]
Hey, my PR got merged into pyinstaller last week. You can update `pyinstaller-hooks-contrib` to get the new hook.
