### ISSUE TITLE
Pretty output

### ISSUE THREAD

**Issue by ijl** [ijl/orjson#59]
This has been requested but needs research. What are the use cases? Is `bytes` output ok? Should it support configurable indent or choose either 2 or 4? What is the API if it is configurable? (Can't specify two conflicting OPT_*.) What settings do major projects like Django, DRF, Flask, etc. use for pretty-printed output? It looks like the formatting around arrays etc. is the same as standard library for a given indentation. What is the performance impact on compact output? What is the performance of orjson and other libraries with pretty output? Needs tests that fixtures print correctly and that any assertions, e.g., it's the same as the standard library's output (nevermind exponents etc), are true.

**Comment by jcushman** [comment]
> What settings do major projects like Django, DRF, Flask, etc. use for pretty-printed output?

DRF lets renderers choose their indent size. The built-in browsable API renderer [defaults to 4](https://github.com/encode/django-rest-framework/blob/master/rest_framework/renderers.py#L412).

DRF also lets *clients* choose an arbitrary indent between 0 and 8 [using the media type header](https://github.com/encode/django-rest-framework/blob/master/rest_framework/renderers.py#L72).

--

My 2 cents: it should be possible to use an arbitrary indent, even if that imposes a performance hit, because it should be *possible* to write a wrapper for a fast json library that matches the output from the built-in library. It doesn't have to be the default, but it should be possible.

That's because it's going to be pretty common for projects to start considering a fast json library when they are already committed to matching built-in `json`'s output.

For example, my current usecase: I made a quick DRF API with vanilla libraries. The API is now getting some traction and is worth profiling, and JSON turns out to be a hotspot so I'm trying to optimize. I'm looking for a fast library that I can write a wrapper function for so the browsable API keeps showing the same output to users. For that I need arbitrary indent, so `orjson` is off the table. Most of the time I serve unindented output, so I don't care if arbitrary indent is super-fast, but I do need it to be there, and I don't want to risk errors by using different libraries for the JSON output consumed by humans and by libraries.

**Comment by ijl** [comment]
Thanks for the input. I think supporting DRF's arbitrary indentation is not worth it. I've implemented support for indenting by two as `OPT_INDENT_2`. This is what serde-json supports upstream. I had in another pull request mentioned using PrettyFormatter--it's `pub` but not exported, and I don't want to maintain another patch or try to upstream arbitrary indentation. If someone wants to do that work for `OPT_INDENT_4`, sure.

**Comment by ijl** [comment]
https://github.com/ijl/orjson/releases/tag/2.6.0
