### ISSUE TITLE
Pypy support

### ISSUE THREAD

**Issue by lewoudar** [ijl/orjson#90]
Hi ijl,
thank you for this amazing piece of software.
I have just one question (and I think you guessed it by the title) , is pypy support planned or not?

Best regards

**Comment by ijl** [comment]
It's come up before so I created https://github.com/ijl/orjson#will-it-support-pypy for this. If you'd like to contribute it that'd be fine. I won't be working on it.

**Comment by pg1671** [comment]
Hi @ijl .. just checking on this as it has been 4 years.  The link in the above comment doesn't go anywhere. But there is a comment on the main page about orjson never supporting pypy.

I am interested in using pypy and the only dependency that won't install under pypy is orjson (out of 100's of packages).

I appreciate your product but it seems strange that a package designed to provide much faster performance for one function (json) is the only one that won't work with a tool like pypy which is all about performance.

I expect I just have to stop using orjson to try pypy? Or is there any chance your stance of this may have changed over the last 4 years.

What is the main reason for this? is the specific use of Cython just fundamental to orjson and how it achieves its performance?

**Comment by jpmckinney** [comment]
The old readme had (per #177):

> Will it support PyPy?
> If someone implements it well.

And another commenter wrote:

> Maye the issue shouldn't be called "fails to build with pypy", but "uses private undocumented functions in cpython's API". I think the concerning part of this issue is that there is no safety or stability guarantee for these functions.

In #72 @ijl wrote:

> If someone wants to handle the differences in datetime implementations and add cfg for the CPython-specific APIs, it would, and I'd accept a patch.

And in #177:

> It would be very involved, so I can only suggest looking at the source. Probably not practical.

So, it sounds like orjson *could* run on PyPy with effort, but it wouldn't be easy.

----

FWIW, I ran `script/pybench loads` on CPython 3.12 and PyPy 3.10 (commenting out code for rapidjson and orjson, and removing python-rapidjson, pandas and seaborn from bench/requirements.txt, since I was having trouble installing those on PyPy on my machine due to missing headers; I also had to remove `os.sched_setaffinity` on macOS).

`json` from the standard library on PyPy is slower than orjson on CPython – but it's either as fast or faster than the others on CPython (except on the canada.json benchmark, where it' s about tied for 3rd with rapidjson).

So, if json serialization/deserialization isn't your worst bottleneck, then switching to PyPy might often still be a performance gain.
