### ISSUE TITLE
Support overriding non default classes

### ISSUE THREAD

**Issue by saulshanabrook** [ijl/orjson#93]
I am trying to serialize some arbitrary Python objects and I want to preserve some differences that are currently elided. Currently, if an object subclasses from a supported type you cannot override it. 

For example, there would be no way to have a custom serialization for `Hi` below:

```python
class Hi(int):
    pass
```

Also, I would like to differentiate between serializing tuples and lists, but this is currently impossible as well. 

Maybe it would be possible to also add the ability to define a `preprocess` function that you would pass in? It would be called on each value before trying to serialize.

**Comment by ijl** [comment]
This is the tradeoff for serializing subclasses. That's a common use case and I think customizing a subclass of a builtin is niche, so I wouldn't make any change. The use case of distinguishing between list and tuple is out of scope for this library because in terms of JSON they are equivalent so I don't see anything standard that can be done. I think people try to solve these problems at a level above with marshalling and validation libraries.

`preprocess` isn't possible because a Python method call is very slow.

**Comment by saulshanabrook** [comment]
Fair if you don't want to include this logic.

I agree that `preprocess` is very slow. However, if this library doesn't implement it, then I just have to do it anyway beforehand.

So if you *did* want to include it in this library, you could just make it optional and obviously not call it if someone hasn't provided it.

The reason I think it could make sense to include it here, is because you already have all the traversal logic here.

If not though, feel free to just close this.

**Comment by aronszanto** [comment]
+1 to this. Especially in the case of dataclasses, where custom serialization (e.g., going beyond `_asdict` is an exceptionally common use case. IMO only allowing something as complex as a dataclass to only be serialized in the default way cuts significantly into the utility of this (awesome!) library. Please consider adding functionality where the `encoder` can override the serialization behavior of dataclasses, even if not builtins like ints.

**Comment by rwarren** [comment]
@saulshanabrook This may not work in your use case, but if you are running into problems with subclassing types that `orjson` supports, an alternative approach can be to use composition vs inheritance.  i.e. "_Has a_" vs "_is a_".

For example, instead of:

```python
class Hi(int):
    pass
```

Implement your H class by composing a wrapper like this:

```python
>>> class H:
...     def __init__(self, v):
...         self.v = v
...     def __add__(self, other):
...         return self.v + other
...     # implement any/all other magic methods you want
... 
>>> x = H(10)
>>> x + 32
42
>>> def default(obj):
...     if isinstance(obj, H):
...         return f"This is an H with value {obj.v}"
...     raise TypeError
... 
>>> orjson.dumps(x, default = default)
b'"This is an H with value 10"'
```

Having to re-implement all the magic methods you want can be annoying/slow, but composition has its advantages.

That example H implementation is obviously _extremely,_ incomplete, but serves the purpose.

**Comment by saulshanabrook** [comment]
Hey @rwarren thank you for your suggestion! It's nice of you to write all that up.

Unfortunately in my case I dont have much control over the data types. I am using this to log and serialize calls to all Python functions, as a form of tracing.

**Comment by ijl** [comment]
Ok, https://github.com/ijl/orjson#opt_passthrough_subclass in 3.1.0.

**Comment by saulshanabrook** [comment]
Wow, thank you @ijl that's great!
