### ISSUE TITLE
Serialise bytes objects directly?

### ISSUE THREAD

**Issue by retnikt** [ijl/orjson#95]
I would like to be able to pass in a `bytes` object and have it output, untouched, by `orjson.dumps`. For example: 
```python
>>> orjson.dumps(b"some_bytes")
b'"some_bytes"'
```
Particularly my use case is for data encoded by Python's standard library `base64` module, which outputs bytes, and it seems wasteful to decode and re-encode this string.

This could be unsafe (i.e. create malformed JSON) if the bytes specified are from user input, so I think it would be wise to have an opt-in parameter to `dumps` to enable this behaviour.

**Comment by ijl** [comment]
I think this would be ok if you or the would-be implementer can exhaustively test and document the behavior. For example, it behaves like a str, it will be escaped, you can create invalid UTF-8, whatever. Yes, it should always be behind a flag. I don't see a case where reading the `bytes` object fails or orjson crashes, so with a disclaimer it's unsafe, ok.

**Comment by aspin** [comment]
+1 interest on this, with a slight modification. I would like to also be able to pass in bytes as a field value of a larger struct (i.e. a dictionary), and have that field untouched by `orjson`.

My use case here is that I'm serializing a whole bunch of JSON objects that are very similar to each other, with the exception of some top level fields (e.g. `{"id": "unique_id", "data": { // complex same object}}`). I'd like to serialize the complex object first, cache that result, then reuse it when `orjson` serializes all the top level fields together.

**Comment by rooterkyberian** [comment]
something to note - `ujson.dumps` has `reject_bytes=False` which works similar to the feature requested and thanks to it it will offer superior performance to the orjson where we have to call `.decode()`.
This is somewhat funny since `orjson` opted to break cross-compatibility by enforcing `bytes` as output of dumps citing very similar reasons AFAIK.

**Comment by rooterkyberian** [comment]
> +1 interest on this, with a slight modification. I would like to also be able to pass in bytes as a field value of a larger struct (i.e. a dictionary), and have that field untouched by `orjson`.
> 

I would like to note these should be different features:
* one should be like in other libraries, i.e. old stdlib json library (python2) and new ujson with reject_bytes=False - i.e. we should take it, and serialize it just like we are serializing strings; lets say option could be `OPT_SERIALIZE_BYTES`
* other should be ONLY when explicitly wrapped , so not only you have to enable hypothetical `OPT_SERIALIZE_UNSAFE` , but you also need to wrap your `bytes` objects with `Unsafe(bytes_obj)` wrapper that explicitly would say you tak all responsiblity for it. You could do it either in the original data stracture or in `default` handler automatically for all `bytes` objects if want all that risk.

the second one is VERY dangerous and akin to what you have in templateing engines, like https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#safe 

We should just "pass" `bytes` as since other libraries support it, but in safe fashion, so it will be very easy for developer to mistake it for same thing and put a ticking bomb in production.

**Comment by elupus** [comment]
Did the possible use case of orjson.Fragment die? Just ran into a need for this in HomeAssistant. We do silly post serialization str.replace(SOME_TEMPLATE_STR, b"preserialized data") to get around it. But it's really ugly.
