### ISSUE TITLE
Support objects with buffer-protocol as an input to loads

### ISSUE THREAD

**Issue by jcrist** [ijl/orjson#99]
Currently the input to `orjson.loads` must be a `bytearray` or a `bytes` object. It would be useful if possible to also support passing in other objects supporting the [buffer protocol](https://docs.python.org/3/c-api/buffer.html).

In my use case, I have a large `bytearray` that contains some serialized json at known offsets. If possible, I'd like to read this in without having to copy it out of the bytearray into a new bytearray that only contains the json. Example:

```python
In [25]: header = b"some bytes before"

In [26]: footer = b"some bytes after"

In [27]: json = orjson.dumps({"key": "val"})

In [28]: data = bytearray(header + json + footer)  # a potentially large bytearray

In [29]: subset = memoryview(data)[len(header):len(header) + len(json)]  # a view on the json data, without a copy

In [30]: bytearray(subset)  # this makes a copy, would be nice to just pass `subset` to loads
Out[30]: bytearray(b'{"key":"val"}')
```

**Comment by ijl** [comment]
That would be fine. `PyMemoryViewObject` needs to be defined and checks made on `flags` or `ob_array`. If it's the wrong type (e.g., a numpy or PIL buffer), it should fall through to a "Input must be..." JSONDecodeError.

**Comment by mattsta** [comment]
I got hit by this too, but for a different reason.

I'm reading JSON in from the network, building it up using [`io.BytesIO()`](https://docs.python.org/3/library/io.html#io.BytesIO), then trying to decode... but `orjson` doesn't like `.getbuffer()` (which is a memoryview of the actual bytes in the object with no copying needed), so we have to use `getvalue()` which copies out bytes we should be able to read without copying.

Looking at the `orjson` source, I saw the same issue as this thread—looks like we need a new `PyMemoryViewObject` detection (and it would also need to be destroyed after pulled from the object because a memoryview can be non-contiguous until you query it, at which point python will copy it all together for you)... 

...but then I looked at pickle.

pickle just asks any object "hey give me your buffer, i don't care what you are" and it works for all types:
https://github.com/python/cpython/blob/80a50368c0e4dc9d56af0ce748dea35c9d96d23f/Modules/_pickle.c#L1212-L1215

My rust ability is below zero (after an hour of trying, I can't get a proof of concept working), but we should be able to replace all of the `decode.rs` `str` vs. `bytes` vs. nothing else with one `GetBuffer()` call (or we could keep the existing str/bytes and use `GetBuffer()` as a catch-all fallback if `GetBuffer()` is slower than `PyBytes_AS_STRING`/`PyByteArray_AsString`):
```rust
    let mut pybuf: pyo3::ffi::Py_buffer = unsafe { mem::uninitialized() };
    ffi!(PyObject_GetBuffer(ptr, &mut pybuf, pyo3::ffi::PyBUF_CONTIG_RO)); // and check for return == 0 for okay
// ...
// release pybuf somewhere else
```

Then the `Py_buffer` has `.buf` for the byte string and `.len` for the length. Though we still need to decrement the reference count (`PyBuffer_Release()`) on the returned buffer structure because it could *potentially*  (but unlikely) hold copied bytes if the underlying buffer wasn't contiguous when the buffer request was made.

**Comment by mattsta** [comment]
also looking around, `websockets` made [this decision](https://github.com/aaugustin/websockets/blob/017a072705408d3df945e333e5edd93e0aa8c706/src/websockets/speedups.c#L15-L60):

```c
static int _PyBytesLike_AsStringAndSize(PyObject *obj, char **buffer,
                                        Py_ssize_t *length) {
    // This supports bytes, bytearrays, and C-contiguous memoryview objects,
    // which are the most useful data structures for handling byte streams.
    // websockets.framing.prepare_data() returns only values of these types.
    // Any object implementing the buffer protocol could be supported, however
    // that would require allocation or copying memory, which is expensive.
    if (PyBytes_Check(obj)) {
        *buffer = PyBytes_AS_STRING(obj);
        *length = PyBytes_GET_SIZE(obj);
    } else if (PyByteArray_Check(obj)) {
        *buffer = PyByteArray_AS_STRING(obj);
        *length = PyByteArray_GET_SIZE(obj);
    } else if (PyMemoryView_Check(obj)) {
        Py_buffer *mv_buf;
        mv_buf = PyMemoryView_GET_BUFFER(obj);
        if (PyBuffer_IsContiguous(mv_buf, 'C')) {
            *buffer = mv_buf->buf;
            *length = mv_buf->len;
        } else {
            PyErr_Format(PyExc_TypeError, "expected a contiguous memoryview");
            return -1;
        }
    } else {
        PyErr_Format(PyExc_TypeError,
                     "expected a bytes-like object, %.200s found",
                     Py_TYPE(obj)->tp_name);
        return -1;
    }

    return 0;
}
```

**Comment by ijl** [comment]
@mattsta thanks for the research, it's helpful.

**Comment by ijl** [comment]
https://github.com/ijl/orjson/releases/tag/3.5.0
